### ISSUE TITLE
implement 0-stor server redesign

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#322]
Tasks that should be done first, and can be done in parallel:

+ [x] create JWT Verifier object, avoid globals and centralize all
      JWT logic in jwt package (issue #310);
    + [x] afterwards, create GRPC middleware to verify JWT (issue #317);
+ [x] create GRPC middleware to gather requests stats (issue #346);
+ [x] rename server/disk package to server/fs and improve (issue #323);
+ [x] redefine the server/db package and its subpackages (issue #324);

Afterwards following tasks should be done in sequence AND in order:

+ [x] implement and use the new server encoding package (issue #325);
+ [x] move all GRPC code to the server/api/grpc package (issue #327);
+ [x] move /cmd/zerostorserver/main.go to /cmd/zstordb/main.go (issue #328);

As a final tasks make sure:

+ [x] that the final notes have been respected, as described in https://github.com/zero-os/0-stor/blob/master/specs/server.md#final-notes;
+ [x] that all work as described in the entire spec document (https://github.com/zero-os/0-stor/blob/master/specs/server.md) has be done;
+ [x] ensure unit tests of server package (and subpackages) have an average code coverage of 80% or more;
