### ISSUE TITLE
implement 0-stor client redesign

### ISSUE THREAD

**Issue by GlenDC** [zero-os/0-stor#386]
Now that we've redesigned/improved the 0-stor server, and have also agreed on the client spec (https://github.com/zero-os/0-stor/blob/master/specs/client.md), it is time to implement the new 0-stor client design. This will happen in steps:

+ [x] 1. Use new encoding library (as to increase performance) (#390);
+ [x] 2. add crypto hash package (#391);
+ [x] 3. provide meta memory client (to be used for testing purposes) (#335);
+ [x] 4. support (optional) private key for all client crypto hash algorithms (#401);
+ [x] 5. allow for (integration of) custom meta encoding format (#400);
+ [x] 6. Remove duplicate label from GRPC interface (#402);
+ [x] 7. Prepare the individual clients (#387, #388, #389);
+ [x] 8. refactor clientStorage (and replicator/distributor) logic into storage types (#392);
+ [x] 9. implement pipeline/processor/config model in 0-stor client module (#393);
+ [x] 10. add missing unit tests to 0-stor client module (#394)
            and improve/bugfix where needed;

**Comment by GlenDC** [comment]
The 0-stor (master) client is planned to have the following API:

```go
type Client interface {
    Write(key []byte, r io.Reader, prevKey []byte) error
    WriteLinked(key, prevKey []byte, r io.Reader) error
    Read(key []byte, w io.Writer) error

    Delete(key []byte) error

    GetStatus(key []byte) (ObjectCheckStatus, error)
    Repair(key []byte) error

    Traverse(ctx context.Context, startKey []byte, fromEpoch, toEpoch int64) (<-chan interface{}, error)
    TraversePostOrder(ctx context.Context, startKey []byte, fromEpoch, toEpoch int64) (<-chan interface{}, error)

    Close() error
}
```

**Comment by GlenDC** [comment]
I start to think that stuff like:

```go
WriteLinked(key, prevKey []byte, r io.Reader) error
Traverse(ctx context.Context, startKey []byte, fromEpoch, toEpoch int64) (<-chan interface{}, error)
TraversePostOrder(ctx context.Context, startKey []byte, fromEpoch, toEpoch int64) (<-chan interface{}, error)
```

Doesn't really belong in the main 0-stor client, as this is more of an optional high-level feature, that can easily be added on top of the system (this is easily proven due to the fact that the Walk function simply makes use of the API of the same client, to implement it.

In a way we want to be able to allow to user to add extra metadata to files if desired. As to allow the user to implement all kind of specialized features they might want.

If we know how to provide this kind of functionality, we could provide the Traverse/Link feature as an extra feature that the user can add to their metadata and API, but that is thus opt-in, and not part of the main API/metadata.
